language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install -r requirements.txt
  - python -m pip install --upgrade bezier
  - pip install codecov
script:
  - pytest
  - pytest --cov=hwb tests
after_success:
  - bash <(curl -s https://codecov.io/bash)